[package]
name = "ibc-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
archway-rpc = { git = "ssh://git@github.com/archway-network/archway-rs-rpc.git", rev = "ade729d3" }
bollard = "0.17.1"
tokio = "1.40.0"

[dev-dependencies]
#archway-proto = { path = "../../../arch3.rs/packages/proto", default-features = false, features = ["cosmwasm", "abstract-any"] }
tokio = { version = "1.40.0", features = ["full", "test-util"] }
ica-demo = { path = "../../contracts/ica-demo", features = ["library"] }
cosmwasm-std = { version = "1.3.1" }
