[package]
name = "litmus_chain"
version = "0.1.0"
edition = "2021"

exclude = ["archway", "test_artifacts"]

[features]
default = []
wasm-sudo = ["test-tube/wasm-sudo"]

[dependencies]
#test-tube = { version = "0.8.0" }
# Working on newest version
test-tube = { git = "https://github.com/osmosis-labs/test-tube.git", rev = "9688c23" }
archway-proto = { version = "0.2.1" }
pbjson-types = "0.7.0"
prost-types = "0.13.3"
cosmwasm-std = { version = "2.1", features = ["stargate"] }
# Used for conversion for coin
cosmwasm-std-legacy = { version = "1.5.5", package = "cosmwasm-std" }

prost = "0.13.3"
serde = "1.0"
serde_json = "1.0"
base64 = "0.22.1"

[dev-dependencies]
cw1-whitelist = "1.1.2"
cosmwasm-schema = "2.0.1"
#network-wars = { git = "https://github.com/archid-protocol/network-wars.git", features = ["library"] }

[build-dependencies]
bindgen = "0.69.1"