[global]
add_to_hermes = false
auto_maintain_config = true
extra_wallets = 0
gaiad_binary = "/go/bin/archwayd"
hdpath = ""
home_dir = "/root/.gm"
ports_start_at = 27000
validator_mnemonic = "guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host"
wallet_mnemonic = "any giant turtle pioneer frequent frown harvest ancient episode junior vocal rent shrimp icon idle echo suspect clean cage eternal sample post heavy enough"

[global.hermes]
binary = "./.hermes/bin/hermes" #change this path according to your setup
config = "./.hermes/config.toml"
log_level = "info"
telemetry_enabled = true
telemetry_host = "127.0.0.1"
telemetry_port = 3001

[archway-1]
ports_start_at = 27010

[archway-2]
ports_start_at = 27020

[node-1]
add_to_hermes = true
network = "archway-1"
ports_start_at = 27030

[node-2]
add_to_hermes = true
network = "archway-2"
ports_start_at = 27040