[global]
log_level = "debug"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false
clear_limit = 50

[mode.packets.ics20_max_memo_size]
enabled = true
size = 32768

[mode.packets.ics20_max_receiver_size]
enabled = true
size = 2048

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[[chains]]
type = "CosmosSdk"
id = "archway-1"
rpc_addr = 'http://localhost:27030'
grpc_addr = 'http://localhost:27032'
rpc_timeout = "10s"
trusted_node = true
account_prefix = "archway"
key_name = "wallet"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 10000000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
allow_ccq = true

[chains.event_source]
mode = "pull"
interval = "500ms"
max_retries = 4

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.001
denom = "stake"

[chains.packet_filter]
policy = "allow"
list = [
    [
        "transfer",
        "channel-0",
    ],
    [
        "ica*",
        "*"
    ],
    [
        "wasm*",
        "*",
    ],
]

[chains.packet_filter.min_fees]

[chains.dynamic_gas_price]
enabled = false
multiplier = 1.1
max = 0.6

[chains.address_type]
derivation = "cosmos"

[chains.excluded_sequences]

[[chains]]
type = "CosmosSdk"
id = "archway-2"
rpc_addr = 'http://localhost:27040'
grpc_addr = 'http://localhost:27042'
rpc_timeout = "10s"
trusted_node = true
account_prefix = "archway"
key_name = ""
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
allow_ccq = true

[chains.event_source]
mode = "pull"
interval = "500ms"
max_retries = 4

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 0.001
denom = "stake"

[chains.packet_filter]
policy = "allow"
list = [
    [
        "transfer",
        "channel-0",
    ],
    [
        "ica*",
        "*",
    ],
]

[chains.packet_filter.min_fees]

[chains.dynamic_gas_price]
enabled = true
multiplier = 1.1
max = 0.6

[chains.address_type]
derivation = "cosmos"

[chains.excluded_sequences]

[tracing_server]
enabled = false
port = 5555
