[package]
name = "archway_test_tube"
version = "0.1.0"
edition = "2021"

exclude = ["archway", "test_artifacts"]

[features]
default = []
wasm-sudo = ["test-tube/wasm-sudo"]

[dependencies]
test-tube.workspace = true
archway-proto = { git = "https://github.com/archway-network/arch3.rs.git", rev = "3551d45" }
pbjson-types = "0.6.0"
prost-types = "0.12.6"
cosmwasm-std = "1.5.5"
prost = "0.12.3"
serde = "1.0"
serde_json = "1.0"
base64 = "0.21.5"

[dev-dependencies]
cw1-whitelist = "1.1.2"
cosmwasm-schema = "2.0.1"
#network-wars = { git = "https://github.com/archid-protocol/network-wars.git", features = ["library"] }

[build-dependencies]
bindgen = "0.69.1"